

# Add the unistd C files to the build


# The remaining sources files depend upon C streams
	
LIBS_CSRCS +=	\
	fiprintf.c			\
	fiscanf.c			\
	iprintf.c			\
	iscanf.c			\
	siprintf.c			\
	siscanf.c			\
	sniprintf.c			\
	vdiprintf.c			\
	viprintf.c			\
	viscanf.c			\
	vsiprintf.c			\
	vsiscanf.c			\
	vsniprintf.c		\
	clearerr.c			\
	fclose.c			\
	fdopen.c			\
	feof.c				\
	ferror.c			\
	fflush.c			\
	fgetc.c			\
	fgetpos.c			\
	fgets.c			\
	fileno.c			\
	findfp.c			\
	flags.c			\
	fopen.c			\
	fprintf.c			\
	fputc.c			\
	fputs.c			\
	fread.c			\
	freopen.c			\
	fscanf.c			\
	fseek.c			\
	fsetpos.c			\
	ftell.c			\
	fvwrite.c			\
	fwalk.c			\
	fwrite.c			\
	getc.c				\
	getchar.c			\
	getc_u.c			\
	getchar_u.c			\
	getdelim.c			\
	getline.c			\
	gets.c				\
	makebuf.c			\
	perror.c			\
	printf.c			\
	putc.c				\
	putchar.c			\
	putc_u.c			\
	putchar_u.c			\
	puts.c				\
	refill.c			\
	remove.c			\
	rename.c			\
	rewind.c			\
	rget.c				\
	scanf.c			\
	sccl.c				\
	setbuf.c			\
	setbuffer.c			\
	setlinebuf.c			\
	setvbuf.c			\
	snprintf.c			\
	sprintf.c			\
	sscanf.c			\
	stdio.c			\
	tmpfile.c			\
	tmpnam.c			\
	ungetc.c			\
	vdprintf.c			\
	vprintf.c			\
	vscanf.c			\
	vsnprintf.c			\
	vsprintf.c			\
	vsscanf.c			\
	wbuf.c				\
	wsetup.c			\
	asprintf.c		\
	fcloseall.c		\
	fseeko.c		\
	ftello.c		\
	getw.c			\
	mktemp.c		\
	putw.c			\
	vasprintf.c	\
	asnprintf.c		\
	clearerr_u.c		\
	dprintf.c		\
	feof_u.c		\
	ferror_u.c		\
	fflush_u.c		\
	fgetc_u.c		\
	fgets_u.c		\
	fgetwc.c		\
	fgetwc_u.c		\
	fgetws.c		\
	fgetws_u.c		\
	fileno_u.c		\
	fmemopen.c		\
	fopencookie.c		\
	fpurge.c		\
	fputc_u.c		\
	fputs_u.c		\
	fputwc.c		\
	fputwc_u.c		\
	fputws.c		\
	fputws_u.c		\
	fread_u.c		\
	fsetlocking.c		\
	funopen.c		\
	fwide.c			\
	fwprintf.c		\
	fwrite_u.c		\
	fwscanf.c		\
	getwc.c			\
	getwc_u.c		\
	getwchar.c		\
	getwchar_u.c		\
	open_memstream.c	\
	putwc.c			\
	putwc_u.c		\
	putwchar.c		\
	putwchar_u.c		\
	stdio_ext.c		\
	swprintf.c		\
	swscanf.c		\
	ungetwc.c		\
	vasnprintf.c		\
	vswprintf.c		\
	vswscanf.c		\
	vwprintf.c		\
	vwscanf.c		\
	wprintf.c		\
	wscanf.c		


