# ----------------------------------------------------------
#
# ----------------------------------------------------------

APPS           := wqlat
EXTRA_INCLUDES +=
EXTRA_CFLAGS   +=
EXTRA_LDFLAGS  += -lpthread

include ../build/bpf.mk
