# ----------------------------------------------------------
#
# ----------------------------------------------------------

APPS           := schedhang
EXTRA_INCLUDES +=
EXTRA_CFLAGS   +=
EXTRA_LDFLAGS  += -lpthread -lrt

include ../build/bpf.mk
