# ----------------------------------------------------------
obj-y += hypervisor.o
obj-y += loader.o
obj-y += mm.o
obj-y += scheduler.c
obj-y += vcpu.o
obj-y += vm.o
# ----------------------------------------------------------
