# ----------------------------------------------------------
obj-y += arch_vcpu.o \
		 arch_vm.o \
		 arch_gic.o \
		 generic_timer.o \
		 handler.o \
		 irq.o \
		 ptable.o \
		 stack_guard.o

# ----------------------------------------------------------
# Assembly objects

obj-y += exception.o \
		 transition.o \
		 vm_control.o

# ----------------------------------------------------------
# GICv3 objects

obj-y += gicv3/
# ----------------------------------------------------------
