#!bin/sh

notify_ok() {
printf "
                _____ _____ _____ ____
 /\__/\ /\  /\ / ___//_  _// ___// __ \
 \  __ \\ \_\ \\___ \ / / / ___\ | __ /
  \_\ \_\\____//____/ \_/ \____\ \_| \/ HYPERX

  LINUX KVM               - $(date +%D)
"
}

uptime() {
    echo "----------------------------------------"
    echo "Booting took $(cut -d' ' -f1 /proc/uptime) seconds"
    echo "----------------------------------------"
}

notify_ok

# environment variables
PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

# mount all fs mentioned in /etc/fstab
mount -a
#
if [ -f "/proc/sys/kernel/hotplug" ];then
    echo /sbin/mdev > /proc/sys/kernel/hotplug
    mdev -s
fi

uptime

# set up eth0
# ip link set eth0 up
