# ----------------------------------------------------------
#
# ----------------------------------------------------------

APPS           := bootstrap
EXTRA_INCLUDES :=
EXTRA_CFLAGS   :=
EXTRA_LDFLAGS  :=

include ../build/bpf.mk
