# ----------------------------------------------------------
#
# ----------------------------------------------------------

APPS           := irqstat
EXTRA_INCLUDES += -I../helpers
EXTRA_CFLAGS   +=
EXTRA_LDFLAGS  +=

include ../build/bpf.mk
