#cross-compilation config

set(CMAKE_SYSTEM_PROCESSOR arm)
set(PROJECT_SYSTEM uniproton)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CROSS_PREFIX "${TOOLCHAIN_PATH}/bin/aarch64-none-elf-" CACHE STRING "")
set(CMAKE_C_COMPILER "${CROSS_PREFIX}gcc" CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER CACHE STRING "")
set(CMAKE_C_FLAGS "-nostdlib -nostdinc")

# vim: expandtab:ts=2:sw=2:smartindent
