/**
 * Hustler's Project
 *
 * File:  smp.S
 * Date:  2024/05/31
 * Usage: Multi-processor Implementation
 */

/* Common register usage in this file:
 *  x0  -
 *  x1  -
 *  x2  -
 *  x3  -
 *  x4  -
 *  x5  -
 *  x6  -
 *  x7  -
 *  x8  -
 *  x9  -
 *  x10 -
 *  x11 -
 *  x12 -
 *  x13 -
 *  x14 -
 *  x15 -
 *  x16 -
 *  x17 -
 *  x18 -
 *  x19 -
 *  x20 -
 *  x21 -
 *  x22 -
 *  x23 - UART address
 *  x24 -
 *  x25 -
 *  x26 -
 *  x27 -
 *  x28 -
 *  x29 -
 *  x30 - lr
 */

// --------------------------------------------------------------



// --------------------------------------------------------------
